name: devel
channels:
  - conda-forge
  - conda-forge/label/testing
  - anaconda
dependencies:
  - python=3.11
  - numpy>=1.15
  - pyside2>=5.12
  - qtpy
  - pytest
  - pytest-xvfb
  # SHARPpy Developers - uncomment below
  # - sphinx
  # - sphinx_rtd_theme
  - requests
  - python-dateutil
  - pyinstaller
  - setuptools
  - certifi
  - pip
  # SHARPpy Developers - uncomment below
  # - pip:
    # - sphinx-prompt
    # - pydocstyle
